name: ZAP Baseline

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Run a passive ZAP baseline scan against your staging/dev URL
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ secrets.ZAP_TARGET }}
          cmd_options: >
            -a         # include alpha passive rules
            -m 1       # max 1 minute spider to stay fast
            -I         # ignore ZAP exit code (we start informational)
          rules_file_name: .zap/rules.tsv
          issue_title: "ZAP Baseline Alerts"
          fail_action: false  # start non-gating

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report_html.html
            report_json.json
