# .github/workflows/welcome.yml
name: Welcome Message

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create welcome message file
        run: echo "Welcome to GitHub Actions 🚀" > test.txt

      - name: Print the welcome message
        run: cat test.txt
