name: Nuclei Scan

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  NUCLEI_TEMPLATES_DIR: ~/.nuclei-templates
  TARGETS: ${{ secrets.NUCLEI_TARGETS }}

jobs:
  nuclei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Nuclei Docker image
        run: docker pull projectdiscovery/nuclei:latest

      - name: Cache Nuclei templates
        id: cache-templates
        uses: actions/cache@v4
        with:
          path: ~/.nuclei-templates
          key: nuclei-templates-${{ runner.os }}-v1

      - name: Update templates (on cache miss)
        if: steps.cache-templates.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.nuclei-templates
          docker run --rm -v $HOME/.nuclei-templates:/root/nuclei-templates projectdiscovery/nuclei:latest \
            -update -ut /root/nuclei-templates

      - name: Ensure templates are up-to-date (fast check)
        run: |
          docker run --rm -v $HOME/.nuclei-templates:/root/nuclei-templates projectdiscovery/nuclei:latest \
            -ut /root/nuclei-templates

      - name: Run Nuclei (informational mode)
        run: |
          echo "${TARGETS}" | tr '\r' '\n' | sed '/^$/d' > targets.txt
          docker run --rm \
            -v $PWD:/work \
            -v $HOME/.nuclei-templates:/root/nuclei-templates \
            projectdiscovery/nuclei:latest \
            -l /work/targets.txt \
            -ud /root/nuclei-templates \
            -rate-limit 50 \
            -nc \
            -stats \
            -jsonl -o /work/nuclei-findings.jsonl

      - name: Summarize into Job Summary
        run: |
          echo "### Nuclei Findings Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -s nuclei-findings.jsonl ]; then
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            # Show top 30 lines for quick glance
            head -n 30 nuclei-findings.jsonl >> $GITHUB_STEP_SUMMARY || true
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "No findings produced." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Nuclei results (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-findings
          path: nuclei-findings.jsonl
