name: Nuclei Scan

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:
  # uncomment for nightly runs
  # schedule:
  #   - cron: "0 1 * * *" # 01:00 UTC

permissions:
  contents: read

concurrency:
  group: nuclei-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nuclei:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      TARGETS: ${{ secrets.NUCLEI_TARGETS }} # newline-separated URLs

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare targets file
        run: |
          echo "${TARGETS}" | tr '\r' '\n' | sed '/^$/d' > targets.txt
          echo "Targets:"
          nl -ba targets.txt

      # Official action handles templates & execution (no custom cache → no tar race)
      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          urls: "targets.txt"
          # Keep PRs quick & non-blocking; add -severity later if you want gating
          flags: "-update -nc -stats -jsonl -o nuclei-findings.jsonl"

      - name: Ensure findings file exists
        run: |
          [ -f nuclei-findings.jsonl ] || touch nuclei-findings.jsonl

      - name: Job summary (first lines)
        run: |
          echo "### Nuclei Findings (preview)" >> $GITHUB_STEP_SUMMARY
          if [ -s nuclei-findings.jsonl ]; then
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            head -n 30 nuclei-findings.jsonl >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "No findings produced." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Upload Nuclei results
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-findings
          path: nuclei-findings.jsonl
