on: 
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_request:
   branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions@checkout@v4
      - name: run tests
        run: npm test