on: 
  push:
    branches:
      - main
      - "release/**"
    paths:
      - "src/**"
  pull_requests:
   branches:
      - main
      - "release/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions@checkout@v4.2.2
      - name: run tests
        uses: npm test